project_id = "fywtqewpvakirzjordhs"

[functions]
[functions.toss-confirm-payment]
verify_jwt = false

[functions.payment-request-info]
verify_jwt = false

[functions.send-single-email]
verify_jwt = false

[functions.send-reset-password]
verify_jwt = false
